package eCommerceSaleTrack.model;

public class Customers {
	protected String customerId;
	protected String customerUniqueId;
	protected String customerZipCodePrefix;
	protected String customerCity;
	protected String customerState;
	
	/**
	 * Construct a Customers instance, with input arguments:
	 * @param customerId is id
	 * @param customerUniqueId is unique id
	 * @param customerZipCodePrefix is zip code
	 * @param customerCity is city
	 * @param customerState is state
	 */
	public Customers(String customerId, String customerUniqueId, String customerZipCodePrefix, String customerCity,
			String customerState) {
		this.customerId = customerId;
		this.customerUniqueId = customerUniqueId;
		this.customerZipCodePrefix = customerZipCodePrefix;
		this.customerCity = customerCity;
		this.customerState = customerState;
	}

	/**
	 * This constructor can be used for creating new records, where the unique id may not be 
	 * assigned yet since it is auto-generated by MySQL.
	 * Construct a Customers instance, with input arguments:
	 * @param customerId is id
	 * @param customerZipCodePrefix is zip code
	 * @param customerCity is city
	 * @param customerState is state
	 */
	public Customers(String customerId, String customerZipCodePrefix, String customerCity,
			String customerState) {
		this.customerId = customerId;
		this.customerZipCodePrefix = customerZipCodePrefix;
		this.customerCity = customerCity;
		this.customerState = customerState;
	}
	
	public String getCustomerId() {
		return customerId;
	}


	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}


	public String getCustomerUniqueId() {
		return customerUniqueId;
	}


	public void setCustomerUniqueId(String customerUniqueId) {
		this.customerUniqueId = customerUniqueId;
	}


	public String getCustomerZipCodePrefix() {
		return customerZipCodePrefix;
	}


	public void setCustomerZipCodePrefix(String customerZipCodePrefix) {
		this.customerZipCodePrefix = customerZipCodePrefix;
	}


	public String getCustomerCity() {
		return customerCity;
	}


	public void setCustomerCity(String customerCity) {
		this.customerCity = customerCity;
	}


	public String getCustomerState() {
		return customerState;
	}


	public void setCustomerState(String customerState) {
		this.customerState = customerState;
	}

	
}
